language: ruby
env:
  - TRAVIS=true
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
before_script:
  - "bundle install"
  - "git clone --bare git://github.com/schacon/simplegit.git tests/example.git"
  - "cd tests/example.git && git repack && cd ../.."
script: "bundle exec rake"
